# Generated by Django 2.2.4 on 2020-11-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
